name: custom_animation_appbar
description: A custom animated SliverAppBar that shows details when expanded and a compact row when collapsed.
version: 2.0.0
homepage: https://github.com/IbrahimElbazz/custom_animation_appbar
repository: https://github.com/IbrahimElbazz/custom_animation_appbar

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
